meta:
  bolo:
    address: (( grab jobs.bolo.networks.bolo1.static_ips[0] ))

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: bolo
    templates:
    - { release: bolo, name: bolo  }
    - { release: bolo, name: dbolo }
    - { release: bolo, name: rrd   }
    - { release: bolo, name: rrdcached }
    - { release: bolo, name: gnossis }
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set bolo networks" ))
    properties:
      dbolo:
        submission: (( grab meta.bolo ))
        collectors:
          - { every: 20s, run: linux }
          - { every: 20s, run: process -n dbolo -m dbolo }
      bolo:
        debug: true
        subscription: (( grab meta.bolo ))
        submission:   (( grab meta.bolo ))
        rrd:
          cached: true
          subscription: (( grab meta.bolo ))
          submission:   (( grab meta.bolo ))
        gnossis:
          cached: true

networks: (( param "please set networks" ))

properties: {}
