meta:
  bolo:
    address: (( grab jobs.bolo.networks.internal.static_ips[0] ))

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: bolo
    instances: 1
    templates:
      - { release: bolo, name: dbolo     }
      - { release: bolo, name: bolo      }

    resource_pool: small
    persistent_disk: 0

    networks:
      - name: internal
        static_ips: (( static_ips 0 ))

  - name: ui
    instances: 1
    templates:
      - { release: bolo, name: ui    }
      - { release: bolo, name: ffd   }
      - { release: bolo, name: dbolo }

    resource_pool: small
    persistent_disk: 4096

    networks:
      - name: internal
        static_ips: (( static_ips 1 ))

  - name: slack
    instances: 1
    templates:
      - { release: bolo, name: dbolo }
      - { release: bolo, name: slack }

    resource_pool: small
    persistent_disk: 0

    networks:
      - name: internal

    properties:
      bolo:
        slack:
          webhook: (( grab $WEBHOOK || "https://localhost/you/need/a/real/webhook/here" ))
          channel: (( grab $CHANNEL || "botspam" ))
          botname: Marco Bolo
          avatar:  robot_face

properties:
  bolo:
    submission:   (( grab meta.bolo ))
    subscription: (( grab meta.bolo ))

networks:
  - name: internal
    subnets: (( param "Please define your Network Subnets" ))
