---
meta:
  name:    bolo
  release: Bolo
  target:  sw
  url:     https://ci.vsphere.starkandwayne.com

  initial_version: 0.1.0

  bosh-lite:
    target: https://10.58.111.44:25555
    deployment: bolo-warden

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   bolo-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/bolo-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/bolo-boshrelease/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/bolo-boshrelease/slack:webhook" ))
    channel: '#botspam'

# custom env vars that the build needs
# THIS IS VERY BRITTLE, BUT IT DOES WORK...
jobs:
  - name: testflight
    plan:
      - do:
        - {}
        - task: testflight
          config:
            params:
              WEBHOOK: (( vault "secret/pipelines/bolo-boshrelease/slack:webhook" ))
              CHANNEL: botspam
